//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_ctv_tiepthi
    {
        public long id { get; set; }
        public Nullable<long> booking_id { get; set; }
        public Nullable<long> ctv_id { get; set; }
        public string utm_code { get; set; }
    }
}
