//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_to_driver
    {
        public long id { get; set; }
        public Nullable<double> lon_from { get; set; }
        public Nullable<double> lat_from { get; set; }
        public Nullable<double> lon_to { get; set; }
        public Nullable<double> lat_to { get; set; }
        public string from_place { get; set; }
        public string to_place { get; set; }
        public string car_type_made_model { get; set; }
        public string car_hire_type { get; set; }
        public Nullable<long> driver_id { get; set; }
        public string driver_name { get; set; }
        public Nullable<System.DateTime> date_booking { get; set; }
        public Nullable<int> price_driver { get; set; }
        public Nullable<double> distance { get; set; }
        public Nullable<decimal> total_money { get; set; }
        public string customer_name { get; set; }
        public string customer_phone { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<int> car_size_driver { get; set; }
        public string email_cus { get; set; }
    }
}
