//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public long id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public string des { get; set; }
        public Nullable<long> driver_phone { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string car_from { get; set; }
        public string car_to { get; set; }
        public string car_type { get; set; }
        public string car_hire_type { get; set; }
        public Nullable<int> car_size { get; set; }
        public Nullable<double> lon1 { get; set; }
        public Nullable<double> lat1 { get; set; }
        public Nullable<double> lon2 { get; set; }
        public Nullable<double> lat2 { get; set; }
        public Nullable<int> status2 { get; set; }
    }
}
