//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class call_log
    {
        public long id { get; set; }
        public string phone { get; set; }
        public Nullable<int> calls { get; set; }
        public Nullable<int> app { get; set; }
        public Nullable<int> web { get; set; }
    }
}
