//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class call_driver_log
    {
        public long id { get; set; }
        public string from_number { get; set; }
        public string to_number { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
