//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_price_da_nang
    {
        public int id { get; set; }
        public Nullable<int> car_type { get; set; }
        public Nullable<int> g1 { get; set; }
        public Nullable<int> g2 { get; set; }
        public Nullable<int> g3 { get; set; }
        public Nullable<int> g4 { get; set; }
        public Nullable<int> g5 { get; set; }
        public Nullable<int> g6 { get; set; }
        public Nullable<int> g7 { get; set; }
    }
}
