//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctv_tiepthi
    {
        public long ctv_id { get; set; }
        public string ctv_fullname { get; set; }
        public string ctv_sex { get; set; }
        public Nullable<System.DateTime> ctv_date { get; set; }
        public string ctv_phone { get; set; }
        public string ctv_email { get; set; }
        public string ctv_pass { get; set; }
        public Nullable<int> point_share { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
