//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver_rate_comment
    {
        public long cus_cm_id { get; set; }
        public Nullable<long> cus_driver_id { get; set; }
        public Nullable<int> cus_rate { get; set; }
        public string cus_name { get; set; }
        public string cus_email { get; set; }
        public string cus_phone { get; set; }
        public string cus_comment { get; set; }
        public Nullable<int> cm_like { get; set; }
        public Nullable<int> cm_dislike { get; set; }
        public Nullable<System.DateTime> cm_date { get; set; }
    }
}
