//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public long id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string car_model { get; set; }
        public string car_made { get; set; }
        public Nullable<int> car_years { get; set; }
        public Nullable<int> car_size { get; set; }
        public string car_number { get; set; }
        public string car_type { get; set; }
        public Nullable<int> car_price { get; set; }
        public Nullable<decimal> total_moneys { get; set; }
        public string province { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string code { get; set; }
        public string address { get; set; }
        public string regId { get; set; }
        public Nullable<int> os { get; set; }
        public string pass { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
        public System.Data.Entity.Spatial.DbGeography geo { get; set; }
    }
}
