//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver_search
    {
        public int id { get; set; }
        public string url_search { get; set; }
        public Nullable<int> count_view { get; set; }
        public string search_from { get; set; }
        public string search_to { get; set; }
        public Nullable<int> driver_size { get; set; }
    }
}
