//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class drivers_money
    {
        public int id { get; set; }
        public Nullable<long> driver_id { get; set; }
        public Nullable<int> total_money { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
