//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver_car_price
    {
        public long id { get; set; }
        public Nullable<int> cp_car_type { get; set; }
        public Nullable<int> cp_price { get; set; }
        public Nullable<int> cp_night { get; set; }
        public Nullable<int> cp_multiple { get; set; }
        public Nullable<int> cp_multiple2 { get; set; }
        public Nullable<long> driver_id { get; set; }
    }
}
