//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver_promotion
    {
        public int id { get; set; }
        public Nullable<long> driver_id { get; set; }
        public string des { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
