//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class find_bus
    {
        public long id { get; set; }
        public string bus_no { get; set; }
        public string bus_des { get; set; }
        public string bus_from { get; set; }
        public string bus_to { get; set; }
        public string bus_type { get; set; }
        public string province { get; set; }
    }
}
