//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public long id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string customer_name { get; set; }
        public string sex { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> time_to_pick { get; set; }
        public Nullable<System.DateTime> time_to_pay { get; set; }
        public string pickup { get; set; }
        public string paypoints { get; set; }
        public Nullable<int> so_cho { get; set; }
        public string form { get; set; }
        public string driver { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> vat { get; set; }
        public Nullable<double> sum { get; set; }
        public string note { get; set; }
    }
}
