//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tai_xe_toan_cau
    {
        public long F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public Nullable<double> F9 { get; set; }
        public Nullable<double> F10 { get; set; }
        public Nullable<double> F11 { get; set; }
        public Nullable<double> F12 { get; set; }
        public string F13 { get; set; }
        public Nullable<double> F14 { get; set; }
        public string F15 { get; set; }
    }
}
