//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tnotice
    {
        public int id { get; set; }
        public Nullable<int> tobject { get; set; }
        public string regid { get; set; }
        public Nullable<int> os { get; set; }
        public string title { get; set; }
        public string body { get; set; }
    }
}
